nama = str(input("Masukan Nama Anda : "))
tempat_tinggal = str(input("Tempat Tinggal : "))
nama_ayah = str(input("Nama Ayah : "))
nama_ibu = str(input("Nama Ibu : "))
status = str(input("Status : "))

print (nama)
print (tempat_tinggal)
print (nama_ayah)
print (nama_ibu)
print (status)